# Change these first
owner: buttercrab # Your GitHub username
repo: status.buttercrab.net # Your GitHub repository name

# Add your sites here
sites:
  - name: Bitwarden
    url: https://bitwarden.buttercrab.net
  - name: Code Server
    url: https://code-server.buttercrab.net
  - name: Owncloud
    url: https://owncloud.buttercrab.net
  - name: Jetbrains Hub
    url: https://hub.buttercrab.net
  - name: Jetbrains Teamcity
    url: https://teamcity.buttercrab.net/app/rest/server
  - name: Jetbrains Upsource
    url: https://upsource.buttercrab.net
  - name: Jetbrains Youtrack
    url: https://youtrack.buttercrab.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.buttercrab.net
  apiBaseUrl: https://api.github.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Status of buttercrab.net services"
  introMessage: Status of buttercrab.net services
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
